import autoSteer from "../icons/AutoSteerConf.png";
import snapLeft from "../icons/SnapLeft.png";
import snapRight from "../icons/SnapRight.png";
import manualTurnLeft from "../icons/manualTurnLeft.png";
import manualTurnRight from "../icons/manualTurnRight.png";
import youTurn from "../icons/YouTurnNo.png";
import center from "../icons/center.png";
import curveLine from "../icons/CurveOff.png";
import manualSection from "../icons/ManualOff.png";
import autoSection from "../icons/SectionMasterOff.png";
import abLine from "../icons/ABLineOff.png";
import hydraulicLift from "../icons/HydraulicLiftOff.png";
import headland from "../icons/HeadlandOff.png";
import uTurnLeft from "../icons/uTurnLeft.png";
import uTurnRight from "../icons/uTurnRight.png";

export const aogButtonsList = [
  {
    buttonName: "1",
    name: "section1",
    imagePath: "",
    type: "ACTION",
    params: "",
    id: 1,
    cssClassName: "sections",
    buttonState: null,
  },

  {
    buttonName: "2",
    name: "section2",
    imagePath: "",
    type: "ACTION",
    params: "",
    id: 2,
    cssClassName: "sections",
    buttonState: null,
  },
  {
    buttonName: "3",
    name: "section3",
    imagePath: "",
    type: "ACTION",
    params: "",
    id: 3,
    cssClassName: "sections",
    buttonState: null,
  },
  {
    buttonName: "uTurn",
    name: "uTurnToggle",
    imagePath: youTurn,
    type: "ACTION",
    params: "",
    id: 4,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "center",
    name: "centerButton",
    imagePath: center,
    type: "ACTION",
    params: "",
    id: 5,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "AutoSection",
    name: "sectionAutoToggle",
    imagePath: autoSection,
    type: "ACTION",
    params: "",
    id: 6,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "ManualSection",
    name: "sectionManualToggle",
    imagePath: manualSection,
    type: "ACTION",
    params: "",
    id: 7,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "autoSteerToggle",
    name: "autoSteerToggle",
    imagePath: autoSteer,
    type: "ACTION",
    params: "",
    id: 8,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "uTurnDirectionToggle",
    name: "uTurnDirectionToggle",
    imagePath: { left: uTurnLeft, right: uTurnRight },
    type: "ACTION",
    params: "",
    id: 9,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "manualUTurnRight",
    name: "manualUTurnRight",
    imagePath: manualTurnRight,
    type: "ACTION",
    params: "",
    id: 10,
    cssClassName: "rightSideErrorDistance",
    buttonState: null,
  },
  {
    buttonName: "manualUTurnLeft",
    name: "manualUTurnLeft",
    imagePath: manualTurnLeft,
    type: "ACTION",
    params: "",
    id: 11,
    cssClassName: "leftSideErrorDistance",
    buttonState: null,
  },
  {
    buttonName: "lineABButton",
    name: "lineABButton",
    imagePath: abLine,
    type: "ACTION",
    params: "",
    id: 12,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "curveLine",
    name: "curveLineButton",
    imagePath: curveLine,
    type: "ACTION",
    params: "",
    id: 13,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "hydraulicLift",
    name: "hydraulicLiftToggle",
    imagePath: hydraulicLift,
    type: "ACTION",
    params: "",
    id: 14,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "moveRight",
    name: "moveSnapRightButton",
    imagePath: snapRight,
    type: "ACTION",
    params: "",
    id: 15,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "moveLeft",
    name: "moveSnapLeftButton",
    imagePath: snapLeft,
    type: "ACTION",
    params: "",
    id: 16,
    cssClassName: "control",
    buttonState: null,
  },
  {
    buttonName: "headlandButtonState",
    name: "headlandToggle",
    imagePath: headland,
    type: "ACTION",
    params: "",
    id: 17,
    cssClassName: "control",
    buttonState: null,
  },
];
